const BRAZIL_CITIES = {
  "Acre": ["Rio Branco", "Cruzeiro do Sul"],
  "Alagoas": ["Maceió", "Arapiraca"],
  "Amapá": ["Macapá"],
  "Amazonas": ["Manaus", "Manacapuru"],
  "Bahia": ["Salvador", "Feira de Santana", "Ilhéus", "Vitória da Conquista"],
  "Ceará": ["Fortaleza", "Juazeiro do Norte", "Sobral"],
  "Distrito Federal": ["Brasília"],
  "Espírito Santo": ["Vitória", "Vila Velha", "Cariacica"],
  "Goiás": ["Goiânia", "Anápolis", "Rio Verde"],
  "Maranhão": ["São Luís", "Imperatriz"],
  "Mato Grosso": ["Cuiabá", "Rondonópolis"],
  "Mato Grosso do Sul": ["Campo Grande", "Dourados"],
  "Minas Gerais": ["Belo Horizonte", "Uberlândia", "Juiz de Fora", "Contagem"],
  "Pará": ["Belém", "Santarém", "Marabá"],
  "Paraíba": ["João Pessoa", "Campina Grande"],
  "Paraná": ["Curitiba", "Londrina", "Maringá", "Foz do Iguaçu"],
  "Pernambuco": ["Recife", "Caruaru", "Petrolina"],
  "Piauí": ["Teresina", "Parnaíba"],
  "Rio de Janeiro": ["Rio de Janeiro", "Niterói", "Petrópolis", "Volta Redonda"],
  "Rio Grande do Norte": ["Natal", "Mossoró"],
  "Rio Grande do Sul": ["Porto Alegre", "Caxias do Sul", "Pelotas"],
  "Rondônia": ["Porto Velho", "Ji-Paraná"],
  "Roraima": ["Boa Vista"],
  "Santa Catarina": ["Florianópolis", "Joinville", "Blumenau"],
  "São Paulo": ["São Paulo", "Campinas", "Santos", "Ribeirão Preto", "Guarulhos", "Sorocaba", "Artur Nogueira"],
  "Sergipe": ["Aracaju"],
  "Tocantins": ["Palmas"]
};
